---

  - name: Installation de Wireshark
    hosts: all

    tasks:

    # Wireshark pour Debian et RedHat

    - name: Installation de Wireshark Debian
      apt:
        name: wireshark
        state: present
      when: ansible_facts['os_family'] == "Debian"
      become: yes
    
    - name: Installation de Wireshark RedHat
      dnf:
        name: wireshark
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Installation d'nmap + net-tools + whois + bind-utils + tcpdump sur Redhat
      dnf:
        pkg:
          - nmap
          - net-tools
          - whois
          - bind-utils
          - tcpdump
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Installation d'nmap + net-tools + whois + dnsutils + tcpdump sur Debian
      apt:
        pkg:
          - nmap
          - net-tools
          - whois
          - dnsutils
          - tcpdump
        state: present
      when: ansible_facts['os_family'] == "Debian"
      become: yes

    - name: Créer le groupe wireshark s'il n'existe pas
      ansible.builtin.group:
        name: wireshark
        state: present
      become: yes

    - name: Ajout d'antonin au groupe wireshark
      ansible.builtin.user:
        name: antonin
        groups: wireshark
      become: yes

    - name: Redémarrage de la VM
      reboot:
      become: yes