---

  - name: Installation d'une interface graphique pour Linux
    hosts: all
    vars:
        gui: "{{ gui }}"

    tasks:      

    - name: Installation de "{{ gui }}" pour Debian
      apt:
        name: "{{ gui }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"
      become: yes

    - name: Installation de firefox pour xfce (non installé par défaut)
      apt:
        pkg:
        - firefox-esr
        state: present
      when: ansible_facts['os_family'] == "Debian" and gui == "xfce4"
      become: yes
    
    - name: Installation de Gnome pour RedHat (xfce non supporté)
      dnf:
        name: "@workstation"
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Lancement du gestionnaire de fenêtre au démarrage de la VM
      ansible.builtin.shell: systemctl set-default graphical.target
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Activer autologin Gnome Debian
      ansible.builtin.lineinfile:
        path: /etc/gdm3/daemon.conf
        state: present
        regexp: "#  AutomaticLoginEnable = true"
        line: "AutomaticLoginEnable = true"
      when: ansible_facts['os_family'] == "Debian" and gui == "gnome"
      become: yes
    
    - name: Activer autologin Gnome Debian
      ansible.builtin.lineinfile:
        path: /etc/gdm3/daemon.conf
        state: present
        regexp: "#  AutomaticLogin = user1"
        line: "AutomaticLogin = antonin"
      when: ansible_facts['os_family'] == "Debian" and gui == "gnome"
      become: yes

    - name: Activer autologin Gnome RedHat
      copy:
        src: gdm_custom_redhat.conf
        dest: /etc/gdm/custom.conf
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Activer autologin xfce
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        state: present
        regexp: "#autologin-user="
        line: "autologin-user=antonin"
      when: ansible_facts['os_family'] == "Debian" and gui == "xfce4"
      become: yes

    - name: Activer autologin xfce
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        state: present
        regexp: "#autologin-user-timeout=delay"
        line: "autologin-user-timeout=0"
      when: ansible_facts['os_family'] == "Debian" and gui == "xfce4"
      become: yes

    - name: Suppression des répertoires inutiles dans /home/antonin
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/antonin/Documents
        - /home/antonin/Music
        - /home/antonin/Pictures
        - /home/antonin/Public
        - /home/antonin/Templates
        - /home/antonin/Videos

    - name: Désactivation du blank screen Gnome
      ansible.builtin.shell: gsettings set org.gnome.desktop.session idle-delay 0
      when: gui == "gnome"

    - name: Redémarrage de la VM
      reboot:
      become: yes