---

  - name: Configuration minimale des VM Linux
    hosts: all

    tasks:

    - name: Installation de paquets
      apt:
        pkg:
        - vim
        - htop
        - git
        - sudo
      when: ansible_facts['os_family'] == "Debian"
      become: yes      

    - name: Installation de paquets
      dnf:
        name:
          - vim
          - git
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Copie du fichier de configuration de vim
      copy:
        src: vimrc
        dest: /home/antonin/.vimrc

    - name: Copie du fichier de configuration de bash pour Debian
      copy:
        src: bashrc_debian
        dest: /home/antonin/.bashrc
      when: ansible_facts['os_family'] == "Debian"

    - name: Copie du fichier de configuration de bash pour Debian (root)
      copy:
        src: bashrc_debian
        dest: /root/.bashrc
      when: ansible_facts['os_family'] == "Debian"
      become: yes

    - name: Copie du fichier de configuration de bash pour RedHat
      copy:
        src: bashrc_redhat
        dest: /home/antonin/.bashrc
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Copie du fichier de configuration de bash pour RedHat (root)
      copy:
        src: bashrc_redhat
        dest: /root/.bashrc
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Suppression des répertoires inutiles dans /home/antonin
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/antonin/Documents
        - /home/antonin/Music
        - /home/antonin/Pictures
        - /home/antonin/Public
        - /home/antonin/Templates
        - /home/antonin/Videos

    - name: Ajout d'antonin au groupe wheel
      ansible.builtin.user:
        name: antonin
        group: wheel
      when: ansible_facts['os_family'] == "RedHat"
      become: yes

    - name: Ajout d'antonin au groupe sudo
      ansible.builtin.user:
        name: antonin
        group: sudo
      when: ansible_facts['os_family'] == "Debian"
      become: yes

    - name: Suppresion de la demande de mot de passe pour sudo (Debian groupe sudo)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo ALL='
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
      when: ansible_facts['os_family'] == "Debian"
      become: yes

    - name: Suppresion de la demande de mot de passe pour sudo (CentOS groupe wheel)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel ALL='
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
      when: ansible_facts['os_family'] == "RedHat"
      become: yes